[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26.2"
engine_blue = {path="../engine_blue"}
env_logger = "0.11.2"
log = "0.4.20"
